create table public.maintenance_settings (
  id boolean primary key default true check (id),
  enabled boolean not null default false,
  password_hash text,
  password_salt text,
  version integer not null default 1 check (version > 0),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  check (not enabled or (password_hash is not null and password_salt is not null))
);

insert into public.maintenance_settings (id, enabled)
values (true, false)
on conflict (id) do nothing;

create table public.maintenance_attempts (
  id bigint generated by default as identity primary key,
  fingerprint text not null,
  attempted_at timestamptz not null default now()
);

create index maintenance_attempts_fingerprint_time_idx
  on public.maintenance_attempts (fingerprint, attempted_at desc);

alter table public.maintenance_settings enable row level security;
alter table public.maintenance_attempts enable row level security;

revoke all on public.maintenance_settings from anon, authenticated;
revoke all on public.maintenance_attempts from anon, authenticated;
grant select, insert, update on public.maintenance_settings to service_role;
grant select, insert, delete on public.maintenance_attempts to service_role;
grant usage, select on sequence public.maintenance_attempts_id_seq to service_role;
